FROM python:3.7

#application port
EXPOSE 8443

# set noninteractive mode to fix errors related to apt-get
RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections

RUN echo "Africa/Cairo" > /etc/timezone

#Download pacjages
RUN apt update -- && apt install -y \
    python \
    git \
    python3-pip \
    python3-setuptools \
    libsm6 \
    libxext6 \
    libxrender1 \
    openjdk-8-jre-headless

# Disable Running performance tests to find the best convolution algorithm for face detection
ENV MXNET_CUDNN_AUTOTUNE_DEFAULT 0

# Install pip requirements
ADD requirements.txt .
RUN pip3 install -r requirements.txt

COPY . /root/

WORKDIR /root/

RUN cd insightface/RetinaFace/rcnn/cython ;  python3 setup.py build_ext --inplace 
RUN model-archiver --model-name r50 --model-path /root/models/detection/retinaface-R50/ --handler /root/models/detection/retinaface-R50/model_handler.py

ENTRYPOINT ["/root/docker-entry_point.sh"]
CMD ["serve"]

           

