FROM tensorflow/tensorflow:1.15.2-gpu

#application port
EXPOSE 5002

# set noninteractive mode to fix errors related to apt-get
RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections

RUN echo "Africa/Cairo" > /etc/timezone

#Download pacjages
RUN apt update -- && apt install -y \
    python \
    git \
    python3-pip \
    python3-setuptools \
    libsm6 \
    libxext6 \
    libxrender1

# Install pip requirements
ADD requirements.txt .
RUN pip3 install -r requirements.txt

COPY . /root/

WORKDIR /root/

ENTRYPOINT  python3 app.py
